# Generated by Django 3.2 on 2026-01-28 16:00:00
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('tarifas', '0001_initial'),
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consulta', models.CharField(max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('PAGADA', 'Pagada'), ('TRIAJE_PENDIENTE', 'Triaje pendiente'), ('EN_TRIAGE', 'En triaje'), ('TRIAJE_COMPLETO', 'Triaje completo'), ('ATENDIDA', 'Atendida')], default='REGISTRADA', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('tratamiento', models.TextField(blank=True, null=True, verbose_name='Tratamiento')),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de atención')),
                ('doctor', models.ForeignKey(blank=True, help_text='Seleccione el médico que atenderá la consulta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctores.doctor', verbose_name='Médico asignado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarifas.tarifaconsulta')),
            ],
        ),
    ]
