# Generated by Django 3.2 on 2026-01-28 16:00:00
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultas', '0002_alter_consulta_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(help_text='Ej: Paracetamol 500mg, Amoxicilina 250mg', max_length=200, verbose_name='Medicamento')),
                ('dosis', models.CharField(help_text='Ej: 500mg, 1 tableta, 5ml', max_length=100, verbose_name='Dosis')),
                ('frecuencia', models.CharField(help_text='Ej: Cada 8 horas, Cada 12 horas, Una vez al día', max_length=100, verbose_name='Frecuencia')),
                ('duracion', models.CharField(help_text='Ej: 7 días, 10 días, Hasta terminar', max_length=100, verbose_name='Duración')),
                ('indicaciones', models.TextField(blank=True, help_text='Ej: Tomar con alimentos, No manejar maquinaria', verbose_name='Indicaciones especiales')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Número total de unidades recetadas', verbose_name='Cantidad recetada')),
                ('cantidad_atendida', models.PositiveIntegerField(default=0, help_text='Unidades que ya se han entregado al paciente', verbose_name='Cantidad atendida')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('PARCIAL', 'Parcialmente atendida')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, help_text='Fecha y hora en que se entregó el medicamento', null=True, verbose_name='Fecha de atención')),
                ('observaciones_farmacia', models.TextField(blank=True, help_text='Notas sobre la dispensación del medicamento', verbose_name='Observaciones de farmacia')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='consultas.consulta', verbose_name='Consulta')),
                ('usuario_atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que atendió')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
