# Generated by Django 5.2.9 on 2026-01-28 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_ordenexamen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se asignó a un técnico', null=True, verbose_name='Fecha de asignación'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, help_text='Personal de laboratorio asignado para procesar esta orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_examen_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Diagnóstico principal de la consulta', null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha_atencion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se atendió la consulta', null=True, verbose_name='Fecha de atención'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones y hallazgos del examen físico', null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tratamiento',
            field=models.TextField(blank=True, help_text='Plan de tratamiento indicado', null=True, verbose_name='Tratamiento'),
        ),
    ]
