# Generated by Django 5.2.9 on 2026-02-03 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0009_ventaambulatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='venta_ambulatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_examen', to='consultas.ventaambulatoria', verbose_name='Venta Ambulatoria'),
        ),
        migrations.AlterField(
            model_name='ordenexamen',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_examen', to='consultas.consulta', verbose_name='Consulta'),
        ),
    ]
