# Generated by Django 5.2.9 on 2026-02-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0010_ordenexamen_venta_ambulatoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenexamen',
            name='tipo_examen',
            field=models.CharField(choices=[('LABORATORIO', 'Laboratorio')], max_length=50, verbose_name='Tipo de Examen'),
        ),
    ]
