# Generated by Django 5.2.9 on 2026-01-15 19:36

import django.core.validators
import triaje.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0003_alter_triaje_frecuencia_cardiaca_alter_triaje_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triaje',
            name='frecuencia_cardiaca',
            field=models.PositiveIntegerField(blank=True, help_text='Latidos por minuto (lpm)', null=True, validators=[django.core.validators.MinValueValidator(30, message='Frecuencia mínima: 30 lpm'), django.core.validators.MaxValueValidator(220, message='Frecuencia máxima: 220 lpm')]),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos (ej: 70.5)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(2, message='El peso mínimo permitido es 2 kg'), django.core.validators.MaxValueValidator(300, message='El peso máximo permitido es 300 kg')]),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='presion',
            field=models.CharField(blank=True, help_text='Presión arterial (ej: 120/80)', max_length=10, validators=[triaje.models.validar_presion]),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='saturacion',
            field=models.PositiveIntegerField(blank=True, help_text='Saturación de oxígeno (%)', null=True, validators=[django.core.validators.MinValueValidator(50, message='Saturación mínima: 50%'), django.core.validators.MaxValueValidator(100, message='Saturación máxima: 100%')]),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='talla',
            field=models.PositiveIntegerField(blank=True, help_text='Talla en centímetros (ej: 170)', null=True, validators=[django.core.validators.MinValueValidator(50, message='La talla mínima permitida es 50 cm'), django.core.validators.MaxValueValidator(250, message='La talla máxima permitida es 250 cm')]),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura corporal en °C (ej: 36.5)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30, message='Temperatura mínima: 30 °C'), django.core.validators.MaxValueValidator(45, message='Temperatura máxima: 45 °C')]),
        ),
    ]
