# Generated by Django 5.2.9 on 2026-01-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0004_alter_triaje_frecuencia_cardiaca_alter_triaje_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triaje',
            name='frecuencia_cardiaca',
            field=models.PositiveIntegerField(blank=True, help_text='Latidos por minuto (lpm)', null=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos (kg)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='saturacion',
            field=models.PositiveIntegerField(blank=True, help_text='Saturación de oxígeno (%)', null=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='talla',
            field=models.PositiveIntegerField(blank=True, help_text='Talla en centímetros (cm)', null=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura corporal en °C', max_digits=4, null=True),
        ),
    ]
