# Generated by Django 5.2.9 on 2026-01-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0005_alter_triaje_frecuencia_cardiaca_alter_triaje_peso_and_more'),
    ]

    operations = [
    ]
