# Generated by Django 5.2.9 on 2026-01-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0006_auto_20260115_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triaje',
            options={'permissions': [('corregir_triaje', 'Puede corregir triajes completados'), ('ver_historial_triaje', 'Puede ver historial de triajes'), ('registrar_triaje', 'Puede registrar triaje')]},
        ),
    ]
