# Generated by Django 5.2.9 on 2026-02-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0002_doctor_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(choices=[('GENERAL', 'Medicina General'), ('ECOGRAFIA', 'Ecografía'), ('PEDIATRIA', 'Pediatría'), ('PSICOLOGIA', 'Psicología'), ('OBSTETRICIA', 'Obstetricia'), ('LECTURA_RESULTADOS', 'Lectura de Resultados')], max_length=20, unique=True),
        ),
    ]
