# Generated by Django 5.2.9 on 2026-02-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0003_alter_especialidad_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidades',
            field=models.ManyToManyField(related_name='doctores', to='doctores.especialidad', verbose_name='Especialidades'),
        ),
    ]
