# Generated by Django 5.2.9 on 2026-02-13 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('DOCTOR', 'Doctor'), ('FARMACIA', 'Farmacia'), ('LABORATORIO', 'Laboratorio')], max_length=20)),
                ('tipo', models.CharField(choices=[('NUEVA_CONSULTA', 'Nueva consulta'), ('NUEVA_RECETA', 'Nueva receta'), ('NUEVO_EXAMEN', 'Nuevo examen')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('elemento_id', models.IntegerField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
