# Generated by Django 5.2.9 on 2026-01-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el paciente está activo en el sistema', verbose_name='¿Activo?'),
        ),
    ]
