# Generated by Django 3.2 on 2026-01-28 16:00:00
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('PAGADA', 'Pagada'), ('TRIAJE_PENDIENTE', 'Triaje pendiente'), ('EN_TRIAGE', 'En triaje'), ('TRIAJE_COMPLETO', 'Triaje completo'), ('ATENDIDA', 'Atendida')], default='REGISTRADA', max_length=20),
        ),
    ]
