# Generated by Django 3.2 on 2026-01-28 16:00:00
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('LABORATORIO', 'Laboratorio'), ('ECOGRAFIA', 'Ecografía'), ('RAYOS_X', 'Rayos X'), ('TOMOGRAFIA', 'Tomografía'), ('RESONANCIA', 'Resonancia Magnética'), ('ELECTROCARDIOGRAMA', 'Electrocardiograma'), ('OTRO', 'Otro')], max_length=50, verbose_name='Tipo de Examen')),
                ('examen_especifico', models.CharField(help_text='Ej: Hemograma completo, Ecografía abdominal', max_length=200, verbose_name='Examen Específico')),
                ('indicaciones', models.TextField(blank=True, help_text='Preparación especial o indicaciones para el examen', verbose_name='Indicaciones')),
                ('urgente', models.BooleanField(default=False, verbose_name='Urgente')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de realización')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado')),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('ENTREGADO', 'Entregado')], default='SOLICITADO', max_length=20)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_solicitados', to='consultas.consulta', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Orden de Examen',
                'verbose_name_plural': 'Órdenes de Examen',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
