# Generated by Django 5.2.9 on 2026-01-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_ordenexamen_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
    ]
