# Generated by Django 5.2.9 on 2026-01-29 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_ordenexamen_fecha_entrega'),
        ('pacientes', '0003_alter_paciente_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-fecha'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='ordenexamen',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_examen', to='consultas.consulta', verbose_name='Consulta'),
        ),
    ]
