# Generated by Django 5.2.9 on 2026-02-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0011_alter_ordenexamen_tipo_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], max_length=20, null=True, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='¿Pagado?'),
        ),
    ]
