# Generated by Django 5.2.9 on 2026-02-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0012_ordenexamen_metodo_pago_ordenexamen_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Pagado'),
        ),
    ]
