# Generated by Django 5.2.9 on 2026-02-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0013_ordenexamen_fecha_pago_ordenexamen_monto_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenexamen',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto Pagado'),
        ),
    ]
