# Generated by Django 5.2.9 on 2026-02-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0014_alter_ordenexamen_monto_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaambulatoria',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento Aplicado (S/)'),
        ),
    ]
