# Generated by Django 5.2.9 on 2026-02-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0015_ventaambulatoria_descuento_aplicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoEcografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Ecografía Abdominal, Ecografía Obstétrica, Ecografía Pélvica', max_length=200, verbose_name='Nombre de la Ecografía')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en soles', max_digits=8, verbose_name='Precio (S/)')),
                ('activo', models.BooleanField(default=True, help_text='¿Esta ecografía está disponible?', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ecografía del Catálogo',
                'verbose_name_plural': 'Catálogo de Ecografías',
                'ordering': ['nombre'],
            },
        ),
    ]
