# Generated by Django 5.2.9 on 2026-01-12 22:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('historial_medico', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historiales_medicos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='fecha_atencion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='indicaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='paciente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='historiales', to='pacientes.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='tratamiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='consulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='consultas.consulta'),
        ),
    ]
