# Generated by Django 5.2.9 on 2026-01-26 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_add_venta_to_movimientoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='venta',
            field=models.ForeignKey(blank=True, help_text='Venta que generó este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.venta', verbose_name='Venta Relacionada'),
        ),
    ]
