# Generated by Django 5.2.9 on 2026-01-26 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_add_venta_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Venta'},
        ),
        migrations.RemoveField(
            model_name='venta',
            name='estado',
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TARJETA', 'Tarjeta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
