# Generated by Django 5.2.9 on 2026-01-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consulta', models.CharField(choices=[('GENERAL', 'Consulta General'), ('ECOGRAFIA', 'Ecografía'), ('ESPECIALIDAD', 'Consulta por Especialidad')], max_length=20)),
                ('especialidad', models.CharField(blank=True, choices=[('PEDIATRIA', 'Pediatría'), ('PSICOLOGIA', 'Psicología'), ('OBSTETRICIA', 'Obstetricia')], max_length=20, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
