# Generated by Django 5.2.9 on 2026-02-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifaconsulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('GENERAL', 'Consulta General'), ('ECOGRAFIA', 'Ecografía'), ('ESPECIALIDAD', 'Consulta por Especialidad'), ('LECTURA_RESULTADOS', 'Lectura de Resultados')], max_length=20),
        ),
    ]
