# Generated by Django 5.2.9 on 2026-03-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0013_add_custom_permissions'),
    ]

    operations = [
    ]
