# Generated by Django 5.2.9 on 2026-01-14 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0002_alter_consulta_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=5)),
                ('talla', models.PositiveIntegerField(help_text='Talla en cm')),
                ('temperatura', models.DecimalField(decimal_places=1, help_text='Temperatura en °C', max_digits=4)),
                ('presion', models.CharField(help_text='Ejemplo: 120/80', max_length=10)),
                ('frecuencia_cardiaca', models.PositiveIntegerField(help_text='Latidos por minuto')),
                ('saturacion', models.PositiveIntegerField(blank=True, help_text='Saturación de oxígeno en %', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='triaje', to='consultas.consulta')),
            ],
        ),
    ]
