# Generated by Django 5.2.9 on 2026-02-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0016_catalogoecografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='es_lectura_resultados',
            field=models.BooleanField(default=False, help_text='Consulta solo para lectura de resultados de exámenes', verbose_name='Es lectura de resultados'),
        ),
    ]
