# Generated by Django 5.2.9 on 2026-02-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0017_consulta_es_lectura_resultados'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=20.0, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
