# Generated by Django 5.2.9 on 2026-02-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0018_topicocatalogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='consulta',
            name='examen_fisico',
            field=models.TextField(blank=True, help_text='Hallazgos del examen físico realizado', null=True, verbose_name='Examen físico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='motivo_consulta',
            field=models.TextField(blank=True, help_text='Síntomas y razón por la que el paciente consulta', null=True, verbose_name='Motivo de consulta'),
        ),
    ]
