# Generated by Django 5.2.9 on 2026-02-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0019_remove_consulta_observaciones_consulta_examen_fisico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenexamen',
            name='urgente',
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='resultado_json',
            field=models.JSONField(blank=True, default=dict, help_text='Almacena los resultados en formato JSON para exámenes con múltiples campos', verbose_name='Resultados estructurados'),
        ),
        migrations.AlterField(
            model_name='ordenexamen',
            name='examen_especifico',
            field=models.CharField(help_text='Ej: Hemograma completo, Glucosa, Perfil lipídico', max_length=200, verbose_name='Examen Específico'),
        ),
        migrations.AlterField(
            model_name='ordenexamen',
            name='resultado',
            field=models.TextField(blank=True, verbose_name='Resultado (texto plano)'),
        ),
        migrations.AlterField(
            model_name='ordenexamen',
            name='tipo_examen',
            field=models.CharField(choices=[('LABORATORIO', 'Laboratorio')], default='LABORATORIO', max_length=50, verbose_name='Tipo de Examen'),
        ),
    ]
