# Generated by Django 5.2.9 on 2026-01-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triaje',
            name='estado',
            field=models.CharField(choices=[('INICIADO', 'Iniciado'), ('COMPLETO', 'Completo')], default='INICIADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='frecuencia_cardiaca',
            field=models.PositiveIntegerField(blank=True, help_text='Latidos por minuto', null=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='presion',
            field=models.CharField(blank=True, help_text='Ejemplo: 120/80', max_length=10),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='saturacion',
            field=models.PositiveIntegerField(blank=True, help_text='Saturación de oxígeno (%)', null=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='talla',
            field=models.PositiveIntegerField(blank=True, help_text='Talla en cm', null=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura en °C', max_digits=4, null=True),
        ),
    ]
