# Generated by Django 5.2.9 on 2026-02-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0007_alter_consulta_options_alter_consulta_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Hemograma completo, Ecografía abdominal, Radiografía de tórax', max_length=200, verbose_name='Nombre del Examen')),
                ('tipo', models.CharField(choices=[('LABORATORIO', 'Laboratorio'), ('ECOGRAFIA', 'Ecografía'), ('RAYOS_X', 'Rayos X'), ('TOMOGRAFIA', 'Tomografía'), ('RESONANCIA', 'Resonancia Magnética'), ('ELECTROCARDIOGRAMA', 'Electrocardiograma'), ('OTRO', 'Otro')], default='LABORATORIO', max_length=50, verbose_name='Tipo de Examen')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en soles', max_digits=8, verbose_name='Precio (S/)')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del examen', verbose_name='Descripción')),
                ('tiempo_entrega', models.CharField(blank=True, help_text='Ej: 24 horas, 48 horas, Inmediato', max_length=100, verbose_name='Tiempo de Entrega')),
                ('preparacion', models.TextField(blank=True, help_text='Instrucciones de preparación para el paciente', verbose_name='Preparación Requerida')),
                ('activo', models.BooleanField(default=True, help_text='¿Este examen está disponible para la venta?', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Examen del Catálogo',
                'verbose_name_plural': 'Catálogo de Exámenes',
                'ordering': ['tipo', 'nombre'],
                'indexes': [models.Index(fields=['tipo', 'activo'], name='consultas_c_tipo_74224f_idx'), models.Index(fields=['nombre'], name='consultas_c_nombre_1a1609_idx')],
            },
        ),
    ]
