# Generated by Django 5.2.9 on 2026-02-03 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_catalogoexamen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaAmbulatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_dni', models.CharField(max_length=15, verbose_name='DNI del Paciente')),
                ('paciente_nombre', models.CharField(max_length=200, verbose_name='Nombre del Paciente')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (S/)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'verbose_name': 'Venta Ambulatoria',
                'verbose_name_plural': 'Ventas Ambulatorias',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
