# Generated by Django 5.2.9 on 2026-01-26 16:34

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría (Analgésicos, Antibióticos, etc.)', max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría', null=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#007bff', help_text='Color para identificar la categoría (hexadecimal)', max_length=7, verbose_name='Color')),
                ('icono', models.CharField(default='fas fa-pills', help_text='Clase de FontAwesome para el ícono', max_length=50, verbose_name='Ícono')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la categoría está disponible', verbose_name='¿Activa?')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'farmacia_categoria',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la presentación', max_length=100, unique=True, verbose_name='Nombre')),
                ('abreviatura', models.CharField(blank=True, help_text='Abreviatura (TAB, CAP, JAR, etc.)', max_length=10, null=True, verbose_name='Abreviatura')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la presentación', null=True, verbose_name='Descripción')),
                ('unidad_medida', models.CharField(default='unidades', help_text='Ej: tabletas, ml, gramos, etc.', max_length=20, verbose_name='Unidad de Medida')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la presentación está disponible', verbose_name='¿Activa?')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'db_table': 'farmacia_presentacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del proveedor', max_length=200, verbose_name='Nombre/Razón Social')),
                ('ruc', models.CharField(help_text='Registro Único de Contribuyente', max_length=11, unique=True, verbose_name='RUC')),
                ('tipo_proveedor', models.CharField(choices=[('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('LABORATORIO', 'Laboratorio'), ('DISTRIBUIDOR', 'Distribuidor')], default='DISTRIBUIDOR', max_length=20, verbose_name='Tipo de Proveedor')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono principal', max_length=15, null=True, verbose_name='Teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, help_text='Teléfono secundario', max_length=15, null=True, verbose_name='Teléfono Alternativo')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico', max_length=254, null=True, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa', null=True, verbose_name='Dirección')),
                ('contacto', models.CharField(blank=True, help_text='Nombre del contacto principal', max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('sitio_web', models.URLField(blank=True, help_text='Página web del proveedor', null=True, verbose_name='Sitio Web')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales', null=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el proveedor está activo', verbose_name='¿Activo?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'farmacia_proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del medicamento', max_length=20, unique=True, verbose_name='Código')),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras (opcional)', max_length=50, null=True, unique=True, verbose_name='Código de Barras')),
                ('nombre_comercial', models.CharField(help_text='Nombre comercial del medicamento', max_length=200, verbose_name='Nombre Comercial')),
                ('nombre_generico', models.CharField(blank=True, help_text='Nombre genérico del principio activo', max_length=200, null=True, verbose_name='Nombre Genérico')),
                ('principio_activo', models.CharField(help_text='Principio activo del medicamento', max_length=200, verbose_name='Principio Activo')),
                ('concentracion', models.CharField(help_text='Concentración del principio activo', max_length=100, verbose_name='Concentración')),
                ('forma_farmaceutica', models.CharField(blank=True, help_text='Ej: Tableta, Cápsula, Jarabe, etc.', max_length=100, null=True, verbose_name='Forma Farmacéutica')),
                ('stock_actual', models.IntegerField(default=0, help_text='Cantidad actual en inventario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(default=10, help_text='Cantidad mínima para alerta de stock bajo', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('stock_maximo', models.IntegerField(default=100, help_text='Cantidad máxima recomendada en inventario', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Stock Máximo')),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='Precio unitario de compra', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio unitario de venta al público', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta')),
                ('precio_venta_mayorista', models.DecimalField(decimal_places=2, default=0, help_text='Precio para ventas al por mayor', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta Mayorista')),
                ('lote', models.CharField(blank=True, help_text='Número de lote del fabricante', max_length=50, null=True, verbose_name='Número de Lote')),
                ('registro_sanitario', models.CharField(blank=True, help_text='Número de registro sanitario', max_length=50, null=True, verbose_name='Registro Sanitario')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del lote actual', null=True, verbose_name='Fecha de Vencimiento')),
                ('fabricante', models.CharField(blank=True, help_text='Nombre del fabricante o laboratorio', max_length=200, null=True, verbose_name='Fabricante/Laboratorio')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del medicamento', null=True, verbose_name='Descripción')),
                ('indicaciones', models.TextField(blank=True, help_text='Indicaciones médicas', null=True, verbose_name='Indicaciones')),
                ('contraindicaciones', models.TextField(blank=True, help_text='Contraindicaciones y precauciones', null=True, verbose_name='Contraindicaciones')),
                ('condiciones_almacenamiento', models.CharField(default='Ambiente fresco y seco', help_text='Temperatura y condiciones recomendadas', max_length=100, verbose_name='Condiciones de Almacenamiento')),
                ('requiere_receta', models.BooleanField(default=False, help_text='Requiere receta médica para su venta', verbose_name='¿Requiere Receta Médica?')),
                ('controlado', models.BooleanField(default=False, help_text='Es un medicamento controlado', verbose_name='¿Medicamento Controlado?')),
                ('refrigerado', models.BooleanField(default=False, help_text='Requiere refrigeración para su almacenamiento', verbose_name='¿Requiere Refrigeración?')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar para ocultar del sistema', verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría del medicamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos', to='farmacia.categoria', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('presentacion', models.ForeignKey(blank=True, help_text='Presentación del medicamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos', to='farmacia.presentacion', verbose_name='Presentación')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Proveedor del medicamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos', to='farmacia.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'farmacia_medicamento',
                'ordering': ['nombre_comercial'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TARJETA', 'Tarjeta')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'farmacia_venta',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('VENTA', 'Venta'), ('DONACION', 'Donación'), ('PERDIDA', 'Pérdida'), ('DEVOLUCION', 'Devolución'), ('TRASLADO', 'Traslado')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(help_text='Cantidad del movimiento', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Precio por unidad al momento del movimiento', max_digits=10, null=True, verbose_name='Precio Unitario')),
                ('referencia', models.CharField(blank=True, help_text='Número de factura, receta, motivo del movimiento, etc.', max_length=255, null=True, verbose_name='Referencia/Motivo')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha y Hora')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True, verbose_name='Observaciones')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='farmacia.medicamento', verbose_name='Medicamento')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('venta', models.ForeignKey(blank=True, help_text='Venta que generó este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.venta', verbose_name='Venta Relacionada')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'farmacia_movimientoinventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.medicamento')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='farmacia.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'farmacia_detalleventa',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['codigo'], name='farmacia_me_codigo_09d82b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['nombre_comercial'], name='farmacia_me_nombre__433c78_idx'),
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['principio_activo'], name='farmacia_me_princip_208a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['activo'], name='farmacia_me_activo_cf8c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['fecha_vencimiento'], name='farmacia_me_fecha_v_987155_idx'),
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['categoria', 'activo'], name='farmacia_me_categor_fc742b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['stock_actual'], name='farmacia_me_stock_a_b9ba06_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha'], name='farmacia_mo_fecha_500588_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo'], name='farmacia_mo_tipo_cf728e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['medicamento', 'fecha'], name='farmacia_mo_medicam_407526_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['usuario', 'fecha'], name='farmacia_mo_usuario_a5db0b_idx'),
        ),
    ]
