# Generated by Django 5.2.9 on 2026-02-23 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_add_usuario_to_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboTopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Combo 1 - Curaciones básicas', max_length=100, verbose_name='Nombre del combo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del combo', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, no aparecerá en las listas', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Combo de tópico',
                'verbose_name_plural': 'Combos de tópico',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComboMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('medicamento', models.ForeignKey(limit_choices_to={'activo': True}, on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicamento', verbose_name='Medicamento')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='farmacia.combotopico', verbose_name='Combo')),
            ],
            options={
                'verbose_name': 'Medicamento del combo',
                'verbose_name_plural': 'Medicamentos del combo',
                'unique_together': {('combo', 'medicamento')},
            },
        ),
    ]
