# Generated by Django 5.2.9 on 2026-02-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0006_combotopico_combomedicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='descripcion',
            field=models.CharField(blank=True, default='', help_text='Descripción del servicio/producto', max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='farmacia.medicamento'),
        ),
    ]
