# Generated by Django 5.2.9 on 2026-02-27 19:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_detalleventa_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='concentracion',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='condiciones_almacenamiento',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='contraindicaciones',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='controlado',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='indicaciones',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='nombre_generico',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='precio_venta_mayorista',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='refrigerado',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='requiere_receta',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='stock_maximo',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='cantidad_por_caja',
            field=models.IntegerField(blank=True, default=1, help_text='Unidades por caja', null=True, verbose_name='Cantidad por caja'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='precio_por_caja',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Precio de venta por caja completa', max_digits=10, null=True, verbose_name='Precio por caja'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría/Grupo del medicamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos', to='farmacia.categoria', verbose_name='Grupo de productos'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras (opcional)', max_length=50, null=True, unique=True, verbose_name='Codigo de barra'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del lote actual', null=True, verbose_name='Fecha de vencimieto'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.CharField(blank=True, help_text='Ej: Tableta, Cápsula, Jarabe, etc.', max_length=100, null=True, verbose_name='presentacion'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='lote',
            field=models.CharField(blank=True, help_text='Número de lote del fabricante', max_length=50, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre_comercial',
            field=models.CharField(help_text='Nombre comercial del medicamento (incluye concentración)', max_length=200, verbose_name='comercial'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, help_text='Precio unitario de compra', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, help_text='Precio unitario de venta al público', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='principio_activo',
            field=models.CharField(blank=True, help_text='Principio activo/compuesto del medicamento', max_length=200, null=True, verbose_name='compuesto'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='registro_sanitario',
            field=models.CharField(blank=True, help_text='Número de registro sanitario', max_length=50, null=True, verbose_name='REGISTRO SANITARIO'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='stock_actual',
            field=models.IntegerField(default=0, help_text='Cantidad actual en inventario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cant.'),
        ),
    ]
