# Generated by Django 5.2.9 on 2026-02-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0008_remove_medicamento_concentracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('VENTA', 'Venta'), ('PERDIDA', 'Pérdida')], max_length=10, verbose_name='Tipo de Movimiento'),
        ),
    ]
