# Generated by Django 5.2.9 on 2026-02-28 17:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0009_alter_movimientoinventario_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Número único de factura del proveedor', max_length=50, unique=True, verbose_name='Número de factura')),
                ('fecha_factura', models.DateField(help_text='Fecha que figura en la factura', verbose_name='Fecha de factura')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IGV (18%)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('archivo_factura', models.FileField(blank=True, help_text='PDF de la factura (opcional)', null=True, upload_to='facturas_compras/%Y/%m/', verbose_name='Archivo de factura')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='farmacia.proveedor', verbose_name='Proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('lote', models.CharField(help_text='Lote del fabricante', max_length=50, verbose_name='Lote')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='farmacia.compra', verbose_name='Compra')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.medicamento', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Detalle de compra',
                'verbose_name_plural': 'Detalles de compra',
            },
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['numero_factura'], name='farmacia_co_numero__5600d3_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['fecha_factura'], name='farmacia_co_fecha_f_45db7e_idx'),
        ),
    ]
