# Generated by Django 5.2.9 on 2026-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0010_compra_detallecompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POSITIVO', 'Ajuste +'), ('AJUSTE_NEGATIVO', 'Ajuste -'), ('VENTA', 'Venta'), ('PERDIDA', 'Pérdida')], max_length=20, verbose_name='Tipo de Movimiento'),
        ),
    ]
