# Generated by Django 5.2.9 on 2026-03-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0011_alter_movimientoinventario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('AJUSTE_POSITIVO', 'Ajuste +'), ('AJUSTE_NEGATIVO', 'Ajuste -'), ('PERDIDA', 'Pérdida')], max_length=20, verbose_name='Tipo de Movimiento'),
        ),
    ]
