# Generated by Django 5.2.9 on 2026-03-09 16:16

from django.db import migrations

def add_custom_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    # 1. Permiso view_triaje para recepción
    try:
        grupo_recepcion = Group.objects.get(name='recepcion')
        # Buscar el permiso por codename
        permiso_triaje = Permission.objects.get(codename='view_triaje')
        grupo_recepcion.permissions.add(permiso_triaje)
        print("✅ Permiso view_triaje agregado a recepción")
    except Exception as e:
        print(f"⚠️ Error con permiso view_triaje: {e}")

def remove_custom_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    # Revertir los cambios
    try:
        grupo_recepcion = Group.objects.get(name='recepcion')
        permiso_triaje = Permission.objects.get(codename='view_triaje')
        grupo_recepcion.permissions.remove(permiso_triaje)
        print("✅ Permiso view_triaje removido de recepción")
    except Exception as e:
        print(f"⚠️ Error al remover: {e}")

class Migration(migrations.Migration):
    dependencies = [
        ('farmacia', '0012_alter_movimientoinventario_tipo'),    
            ]

    operations = [
        migrations.RunPython(add_custom_permissions, remove_custom_permissions),
    ]
