# Generated by Django 5.2.9 on 2026-03-10 19:12
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0013_add_custom_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='medicamento',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='farmacia.Medicamento',
                verbose_name='Medicamento'
            ),
        ),
    ]
