# Generated by Django 5.2.9 on 2026-03-10 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0014_make_medicamento_id_nullable'),
    ]

    operations = [
        # ✅ SOLO lo que realmente necesitas
        migrations.AlterField(
            model_name='detalleventa',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='farmacia.medicamento'),
        ),
    ]
