# Generated by Django 5.2.9 on 2026-03-10 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0016_fix_tipo_length'),
    ]

    operations = [
    ]
