# Generated by Django 5.2.9 on 2026-01-15 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triaje', '0002_triaje_estado_alter_triaje_frecuencia_cardiaca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triaje',
            name='frecuencia_cardiaca',
            field=models.PositiveIntegerField(blank=True, help_text='Latidos por minuto', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg (1–300)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='presion',
            field=models.CharField(blank=True, help_text='Ejemplo: 120/80', max_length=7),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='saturacion',
            field=models.PositiveIntegerField(blank=True, help_text='Saturación de oxígeno (%)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='talla',
            field=models.PositiveIntegerField(blank=True, help_text='Talla en cm (30–250)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura en °C (30–45)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(45)]),
        ),
    ]
