# Generated by Django 5.2.9 on 2026-02-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0002_alter_tarifaconsulta_tipo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifaconsulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('GENERAL', 'Consulta General'), ('ECOGRAFIA', 'Ecografía'), ('ESPECIALIDAD', 'Consulta por Especialidad'), ('LECTURA_RESULTADOS', 'Lectura de Resultados'), ('TOPICO', 'Tópico / Procedimiento')], max_length=20),
        ),
    ]
